### ISSUE TITLE
When I ran "make_tests.sh -sync-media",I got nothing in the dir "external_media"

### ISSUE THREAD

**Issue by chenminnj** [gpac/testsuite#1]
When I ran "make_tests.sh -sync-media",I got nothing in the dir "external_media", and the test suite does not correctly finish .
Is the "http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/" website OK? or  it has changed to another URL?

**Comment by jeanlf** [comment]
we moved our offices and most of our servers are currently down - we'll let you know when they will be back online

**Comment by aureliendavid** [comment]
in the meantime I have a backup that is close to up-to-date that you can download manually [here](https://drive.google.com/open?id=13GIH-mbgNgckU9hIKwROcZ_NCSvJ921C) if you want to try it

**Comment by chenminnj** [comment]
@jeanlf @aureliendavid 
Thank you for your reply,now I can run the test suite correctly.
But When I play this test case's output hvc file "merge3.hvc" ,I get the screen like the below image 
![a](https://user-images.githubusercontent.com/29446122/69241026-c427b700-0bd8-11ea-8d7a-71d0e0e7a5a3.jpg)
The high resolution tile and the low resolution tile is showed in different size. Is there some way to show the merged different resolution tiles in same size?
Thanks!

**Comment by chenminnj** [comment]
why  delete my comment?

**Comment by jeanlf** [comment]
hmm my comment on your deleted comment got deleted as well, strange - I was saying: please repost the comment on the right issue, I cannot find a way to move comments between issues.

**Comment by chenminnj** [comment]
OK,I will create a new issue.  :-)

**Comment by aureliendavid** [comment]
just fyi: test media syncing should now work properly again
