### ISSUE TITLE
Image name should use image width and height and not canvas size

### ISSUE THREAD

**Issue by cconcolato** [gpac/testsuite#16]
https://github.com/gpac/testsuite/blob/87da963fd861a6e0a08ebfb04cfa3bd6a5520920/scripts/ttxtdec.sh#L56

`$OriginalSize$` should probably be replaced by `$Width$x$Height$`

**Comment by jeanlf** [comment]
no, the test is designed to check that `$CropOrigin$` and `$OriginalSize$` properties are set on output pid, the check for width and height is implicit (png encode)
