### ISSUE TITLE
can't run testsuite on windows 10

### ISSUE THREAD

**Issue by pierrextardif** [gpac/testsuite#9]
Hi,

I'm trying to run the testsuite on windows 10, but it returns an error and I can't seem to get the scripts to run:
I'm gettting this error - in MINGW64 - :
`GNU time not found (ret 127) - exiting`

```sh

testsuite (master)
$ ./make_tests.sh
Checking test suite config                                                      - Reference hashes available - enabling hash tests
- External media dir available
GNU time not found (ret 127) - exiting
```
After installing `make` with `scoop` in the powershell, i seems likke there isn't a makefile present to run  `make test_suite` ?

Not sure how to proceed...
Any help would bne appreciated.

Best,

P

**Comment by aureliendavid** [comment]
the script is looking for the gnu time command at /usr/bin/time (which is different from the bash `time` builtin)

you can install the `msys/time` package in msys or something similar

you can see [here](https://github.com/gpac/testsuite/blob/master/make_tests.sh#L396) that it will also look for `date` and `timeout`

**Comment by pierrextardif** [comment]
alright thanks for the prompt response.
Are you using [this guide](https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2), or something similar to run bash commands in windows environement?
My setup isn't ready for MSYS2 yet, and mp4box isn't recognised yet, will report tomorrow once updated.
